LECTURES.push({n:7,title:"Lecture 7: OS Structure, Booting, Processes, Scheduling",
cards:[
["Monolithic (original UNIX)","Kernel is everything below the system-call interface and above the hardware (file system, CPU scheduling, memory management). Plus system programs."],
["Layered approach","OS split into layers: layer 0 is hardware, layer N the user interface. Each layer uses only lower layers."],
["Microkernel","Moves as much as possible from the kernel to user space; modules use message passing. Example: Mach. Easier to extend and port, more reliable and secure; performance overhead."],
["Booting","Execution starts at a fixed location. A bootstrap loader (BIOS in ROM, or UEFI) finds and loads the kernel. GRUB lets you choose a kernel."],
["Process","A program in execution; the unit of execution managed by the kernel (job in batch systems, task in Linux)."],
["Process memory image","Text (code), initialized and uninitialized data, heap, stack (grows downward), command-line arguments and environment at the top."],
["Process states","New, ready, running, waiting, terminated. Admitted, dispatched, I/O request (to waiting), event completes (to ready), preempted (to ready), exit."],
["Process control block (PCB)","Per-process kernel structure to save and restore context: state, PC, registers, scheduling info, memory management, accounting, I/O status."],
["Monolithic details","Original UNIX had limited structuring due to hardware. Two separable parts: system programs and the kernel, with a large number of functions in one level. Linux is monolithic plus modular."],
["Building an OS","Write the source, configure for the target system, compile, install, then boot."],
["Building Linux","Download source; make menuconfig; make (produces vmlinuz, the kernel image); make modules; make modules_install; make install."],
["System boot details","Execution starts at a fixed memory location; a bootstrap loader in ROM loads the kernel. Sometimes two steps: ROM loads a boot block, which loads the bootstrap loader from disk. UEFI replaces BIOS. GRUB selects a kernel; boot states include single user mode."],
["Lights Out Management","Runs on a chipset or separate board while the power cord is plugged in: wake on LAN, remote management, virtual console, reboot/shutdown. Examples: iDRAC, iLO, AMT, iBMC, Intel vPro."],
["Process resources","Code (text), stack (parameters, return addresses, locals), data segment (globals, constants), heap (dynamic memory), plus structures for open files and devices, command-line arguments and environment values."],
["State transitions","new to ready: admitted. ready to running: dispatched. running to waiting: request that cannot be met immediately (I/O). waiting to ready: event completes. running to ready: preempted. running to terminated: exit."],
["PCB and process id","The kernel keeps a PCB for every created, not-yet-destroyed process so it can restore a process to its exact state. Each process has a unique positive integer process id."],
["Scheduling goals","Better hardware utilization, minimal response time, and fairness."],
["Three levels of scheduling","Long-term: which processes are admitted (batch systems). Medium-term: which are memory-resident. Short-term (CPU scheduling): which gets the CPU next."],
["Degree of multiprogramming","Number of processes in memory. Too few: CPU may idle. Too many: not enough memory to perform well. Medium-term scheduling controls it and keeps a good mix."]],
qs:[
["Which are benefits of microkernels?",["Easier to extend","Easier to port","More reliable (less kernel code)","No performance overhead"],[0,1,2],"Moving code to user space makes the OS easier to extend and port and more reliable. The cost is performance overhead."],
["What is the main drawback of microkernels?",["Performance overhead from user/kernel communication","Less secure","Harder to port","Larger kernel"],[0],"Communication between user space and kernel space adds performance overhead."],
["In the layered approach, layer 0 is...",["The hardware","The user interface","The kernel","The scheduler"],[0],"In the layered approach layer 0 is the hardware and layer N is the user interface."],
["Which is an example of a microkernel?",["Mach","MS-DOS","Original UNIX","glibc"],[0],"Mach is the microkernel example. macOS's Darwin is partly based on it."],
["The small ROM code that locates and loads the kernel is the...",["Bootstrap loader (BIOS)","Hypervisor","Shell","Wrapper"],[0],"The bootstrap loader (BIOS, in ROM) locates the kernel, loads it and starts it."],
["Which Linux build step produces vmlinuz?",["make","make menuconfig","make modules_install","make install"],[0],"Plain make compiles the kernel and produces vmlinuz."],
["Which are parts of a process memory image?",["Text segment","Heap","Stack","Process control block"],[0,1,2],"The text segment, heap and stack are part of the memory image. The PCB is a kernel structure."],
["In which direction does the stack grow?",["Downward, toward the data","Upward","Randomly","It does not grow"],[0],"The stack grows downward toward the data, leaving the heap as free space between them."],
["A running process goes back to ready when it is...",["Preempted","Waiting for I/O","Terminated","Admitted"],[0],"Preemption (for example a timer interrupt) takes a process off the CPU and puts it back to ready."],
["A running process that requests I/O moves to which state?",["Waiting","Ready","Terminated","New"],[0],"A request that cannot be satisfied immediately, such as I/O, moves a process to waiting."],
["Which are stored in a PCB?",["Program counter","CPU registers","I/O status information","Heap contents"],[0,1,2],"The PCB holds the PC, CPU registers and I/O status among other info. Heap contents belong to the memory image."],
["Which scheduler decides which memory-resident process gets the CPU next?",["Short-term (CPU) scheduler","Medium-term scheduler","Long-term scheduler","Boot loader"],[0],"Short-term (CPU) scheduling picks which memory-resident process runs next."],
["Original UNIX consists of which two separable parts?",["System programs and the kernel","Shell and GUI","Layer 0 and layer N","Hypervisor and guest"],[0],"Original UNIX had system programs and the kernel as its two separable parts."],
["Linux is best described as...",["monolithic plus modular","a pure microkernel","strictly layered","a simple MS-DOS style"],[0],"Linux is monolithic with loadable modules."],
["In the layered approach, each layer uses...",["only services of lower layers","only services of higher layers","services of any layer","no services"],[0],"Each layer uses only the functions and services of lower layers."],
["Which command configures the Linux kernel?",["make menuconfig","make","make modules","make install"],[0],"make menuconfig is the configuration step."],
["In a two-step boot, ROM code loads...",["a boot block, which loads the bootstrap loader","the GUI","user programs","the hypervisor"],[0],"In a two-step boot, ROM loads a boot block at a fixed location, which loads the bootstrap loader from disk."],
["GRUB allows you to...",["select a kernel from multiple disks or versions","choose kernel options","enter boot states such as single user mode","replace the CPU"],[0,1,2],"GRUB can pick among kernels, set kernel options and boot into states like single user mode."],
["Which are Lights Out Management features?",["Works while the power cord is plugged in","Wake on LAN","Virtual console","Requires the OS to be running"],[0,1,2],"Lights Out Management works whenever power is connected and offers Wake on LAN and a virtual console. It does not need the OS running."],
["A process is...",["a program in execution","a file on disk","a CPU core","a compiled library"],[0],"A process is a program in execution."],
["What moves a process from waiting to ready?",["The awaited event completing","Being dispatched","Being preempted","Exiting"],[0],"When the awaited event completes, the process returns to ready."],
["Which scheduling level decides which processes are admitted?",["Long-term","Medium-term","Short-term","Dispatch"],[0],"Long-term scheduling decides which processes are admitted, usually in batch systems."],
["If too few processes are in memory...",["the CPU might be idle","processes lack memory","fairness is guaranteed","the PCB grows"],[0],"Too few processes in memory means the CPU may sit idle."],
["Which are goals of process scheduling?",["Better hardware utilization","Minimize response time","Achieve fairness","Maximize kernel size"],[0,1,2],"Scheduling aims for better utilization, short response time and fairness."]]});
