LECTURES.push({n:3,title:"Lecture 3: Buses, Networks, Virtualization",
cards:[
["Types of buses","Processor-memory (short, fast, proprietary); I/O bus (long, slower, SCSI/USB/Firewire); backplane (intermediary, e.g. ATA, PCIexpress)."],
["Synchronous bus","Has a clock in its control lines. Little logic, very fast, but all devices share one clock rate and it cannot be long (clock skew)."],
["Asynchronous bus","No clock; uses handshaking (ReadReq, Ack, DataRdy). Handles varied devices and longer lengths, but slower."],
["Bus arbitration goals","Balance bus priority (highest priority first) and fairness (lowest priority never locked out)."],
["Daisy chain vs centralized parallel","Daisy chain: simple but unfair and slower. Centralized parallel: flexible, can assure fairness, but more complex arbiter."],
["Internet protocol stack","Application (FTP, SMTP, HTTP), transport (TCP, UDP), network (IP, routing), link (Ethernet, WiFi, PPP), physical."],
["Packet transmission delay","L (bits) / R (bits/sec): time to push an L-bit packet onto a link of rate R."],
["Hypervisor (VMM)","Software that maps virtual resources (memory, I/O, CPUs) to physical ones. The guest OS may differ from the host OS."],
["Network nuts and bolts","Hosts (end systems) run network apps; communication links (fiber, copper, radio, satellite) are measured by bandwidth; packet switches (routers, switches) forward packets."],
["Async read handshake","Device raises ReadReq with addr; memory reads it and raises Ack; device releases ReadReq; memory drops Ack; memory puts data on lines and raises DataRdy; device reads, raises Ack; memory drops DataRdy; device drops Ack."],
["Access networks","Home: cable/DSL modem, router/firewall/NAT, wireless AP (~600 Mbps), wired Ethernet. Enterprise: Ethernet switches, 10 Mbps to 100 Gbps. Wireless LAN: ~100 ft, 802.11. Wide-area cellular: 10s of km, 3G/4G/5G."],
["Host sending function","Breaks an application message into packets of L bits and sends at link rate R (link capacity = link bandwidth). Transmission delay = L/R."],
["Coax and fiber","Coax: two concentric copper conductors, bidirectional, broadband (HFC). Fiber: light pulses, each a bit; high-speed point-to-point, low error rate, repeaters far apart, immune to electromagnetic noise."],
["Radio links","No physical wire, bidirectional; affected by reflection, obstruction, interference. Types: terrestrial microwave, LAN (WiFi), wide-area (cellular), satellite (~270 ms delay; geosynchronous vs low altitude)."],
["Encapsulation","Each layer adds a header: message, segment (Ht), datagram (Hn), frame (Hl). Switches handle link/physical, routers add the network layer, and the destination decapsulates."],
["Client-server","Server: always-on, permanent IP address, data centers for scaling. Clients: talk to the server, may be intermittently connected, may have dynamic IPs, do not talk directly to each other."],
["P2P architecture","No always-on server; peers communicate directly, requesting and providing service. Self scalability: new peers add capacity and demand. Peers are intermittent and change IPs, so management is complex."],
["Virtualization pros and cons","Host emulates guest OS and resources. Benefits: improved isolation, aids resource sharing. Security and reliability are more a challenge than a feature. Some performance impact. Examples: AWS, Azure, VMware, VirtualBox."]],
qs:[
["Which bus is short, high speed, and matched to the memory system?",["Processor-memory bus","I/O bus","Backplane bus","USB"],[0],"It is optimized for cache block transfers."],
["Which are advantages of an asynchronous bus?",["Accommodates a wide range of device speeds","Can be lengthened without clock skew problems","Faster than a synchronous bus","Needs no handshaking"],[0,1],"It is slower and needs handshaking."],
["Why can a fast synchronous bus not be long?",["Clock skew","Handshaking overhead","Wired-OR","Fairness"],[0],"Devices must stay in step with the clock."],
["Which are disadvantages of daisy chain arbitration?",["Cannot assure fairness","Slower; the grant signal limits speed","Complicated arbiter hardware","Needs a separate line per device"],[0,1],"Its advantage is simple hardware."],
["Which arbitration scheme can assure fairness but needs a more complicated arbiter?",["Centralized parallel","Daisy chain","Software poll","Wired-OR"],[0],"It is also flexible."],
["How long does a 1000-bit packet take on a 1 Mbps link?",["1 ms","1 s","10 ms","0.1 ms"],[0],"1000 / 1,000,000 = 0.001 s."],
["Which layer includes TCP and UDP?",["Transport","Network","Link","Application"],[0],"Process-to-process transfer."],
["Which layer routes datagrams from source to destination?",["Application","Transport","Network","Link"],[2],"IP and routing protocols."],
["Which are true of clients in client-server?",["May be intermittently connected","May have dynamic IP addresses","Do not communicate directly with each other","Always on with a permanent IP"],[0,1,2],"Servers are always on with permanent IPs."],
["Which are guided media?",["Copper","Fiber","Coax","Radio"],[0,1,2],"Radio is unguided."],
["Which is true of hypervisors?",["The guest OS may differ from the host OS","Guest code runs in privileged mode","They remove all performance impact","They need identical OSes"],[0],"Virtualization has some performance impact."],
["Which twisted pair category supports 10 Gbps?",["Category 6/6A","Category 5","Category 8","None"],[0],"Cat 5: 100 Mbps/1 Gbps; Cat 8: 25/40 Gbps."],
["In the async read handshake, who raises ReadReq?",["The I/O device","The memory","The bus arbiter","The CPU clock"],[0]],
["When does memory raise DataRdy?",["After placing data on the data lines","When it sees ReadReq","After the device drops Ack","Before reading addr"],[0]],
["In enterprise networks, end systems typically connect into...",["An Ethernet switch","A cable modem","A satellite","A hypervisor"],[0]],
["Wireless LANs typically cover...",["Within a building (~100 ft)","10s of km","The whole globe","Only one room"],[0]],
["Which are properties of fiber?",["Immune to electromagnetic noise","Low error rate","High-speed point-to-point","Two concentric copper conductors"],[0,1,2],"Concentric copper is coax."],
["Which affect radio links?",["Reflection","Obstruction by objects","Interference","Immunity to noise"],[0,1,2]],
["Typical satellite end-to-end delay is about...",["270 ms","27 ms","2.7 ms","2.7 s"],[0]],
["The unit of data at the network layer is a...",["Datagram","Segment","Frame","Message"],[0]],
["Which are true of P2P?",["Self scalability","No always-on server","Complex management due to changing IPs","Peers have permanent IPs"],[0,1,2]],
["Which are benefits of virtualization?",["Improved isolation of guests","Aids sharing of resources","No performance impact","Removes all security concerns"],[0,1]]]});
