LECTURES.push({n:5,title:"Lecture 5: OS Services, Interfaces, System Calls, APIs",
cards:[
["User-helpful OS services","User interface, program execution, I/O operations, file-system manipulation, communications, error detection."],
["Resource-sharing services","Resource allocation, accounting, protection and security."],
["Communication methods","Shared memory or message passing (packets moved by the OS)."],
["Shell","A command-line interpreter in UNIX and a full programming language. Examples: bash, csh, sh."],
["Built-in vs system program","Built-in: in the shell itself (cd, read). System program: separate executable (grep, date). Both: echo, kill, pwd."],
["Batch processing","Users submit jobs that run without interaction. A monitor reads the batch, then schedules and runs jobs one by one."],
["System call","A call into kernel code via a software interrupt or trap; how a user process requests a kernel service."],
["Wrapper function and API","Wrapper: user-level library function (user mode) whose purpose is to make the system call. API: specifies functions for obtaining kernel services (WinAPI, POSIX, Java)."],
["Program execution and I/O","OS loads a program into memory, runs it, and ends it normally or abnormally (error). A running program may need I/O involving a file or device."],
["File-system manipulation","Programs read, write, create, delete and search files and directories, list file information, and manage permissions."],
["Error detection","OS constantly watches for errors in CPU, memory, I/O devices and user programs and takes appropriate action for correct, consistent computing. Debugging facilities help."],
["Resource allocation","With multiple users or jobs, resources (CPU cycles, main memory, file storage, I/O devices) must be allocated to each."],
["Protection vs security","Protection: all access to system resources is controlled, and concurrent processes do not interfere. Security: defends against outsiders via user authentication and guarding external I/O devices."],
["CLI details","Fetches a command and executes it. Lives in the kernel or in system programs; multiple flavors are shells. If commands are program names, adding features needs no shell change. An interpreter is a stand-alone program; a CLI is more general (MATLAB has a CLI, not an interpreter)."],
["GUI","Desktop metaphor with mouse, keyboard, monitor and icons; invented at Xerox PARC. Windows: GUI plus CLI shell. macOS: Aqua GUI over a UNIX kernel. Unix/Linux: CLI with optional GUI (CDE, KDE, GNOME) on X11 or Wayland."],
["User interface types","CLI (direct command entry), GUI, touchscreen, batch."],
["Wrapper mechanics","The program calls foo(), the library wrapper; inside it, code switches to kernel mode and jumps to the system call handler, which invokes the real kernel function. Technically the wrapper defined in the API is what programs call."]],
qs:[
["Which are services that help the user?",["File-system manipulation","Program execution","Communications","Accounting"],[0,1,2],"File-system manipulation, program execution and communications help the user. Accounting supports efficient system operation."],
["How can processes communicate?",["Shared memory or message passing","Only through files","Only through interrupts","They cannot"],[0],"Processes exchange information through shared memory or message passing."],
["Which is a built-in bash command?",["cd","grep","date","top"],[0],"cd is built into bash. grep and date are separate executables in /bin."],
["grep and date are implemented as...",["System programs (separate executables)","Shell built-ins","Kernel functions","Wrapper functions"],[0],"They live in files (/bin/grep, /bin/date), so they are system programs."],
["Which commands are implemented both ways?",["echo","kill","pwd","cd"],[0,1,2],"echo, kill and pwd exist as both built-ins and executables. cd is only built in."],
["Users interact with a batch processing system through...",["A monitor","A GUI","A shell","A wrapper"],[0],"A monitor reads the batch, then schedules and runs jobs one after another."],
["The GUI was invented at...",["Xerox PARC","Bell Labs","MIT","IBM"],[0],"The GUI desktop metaphor was invented at Xerox PARC."],
["A system call is made via...",["A software interrupt or trap","A plain jump in user mode","A DMA transfer","A shell built-in"],[0],"A system call is made through a software interrupt or trap into the kernel."],
["In which mode does a wrapper function run?",["User mode","Kernel mode","Both at once","Neither"],[0],"The wrapper is part of a user-level library and runs in user mode. The system call itself runs in kernel mode."],
["Which are common APIs?",["WinAPI","POSIX API","Java API","MS-DOS API"],[0,1,2],"WinAPI, POSIX and the Java API are the three common APIs. MS-DOS is an OS structure example."],
["The POSIX API is used by which systems?",["Linux","macOS","UNIX","Windows"],[0,1,2],"POSIX covers UNIX, Linux and macOS. Windows uses WinAPI."],
["What is glibc?",["C library with wrappers for Linux system calls","A shell","A file system","A scheduler"],[0],"glibc is the GNU C library, with wrappers for nearly all Linux system calls."],
["Tracking which users use how much of which resources is...",["Accounting","Protection","Error detection","Program execution"],[0],"Accounting records which users use how much and what kinds of resources."],
["Which are resources the OS allocates?",["CPU cycles","Main memory","I/O devices","Compiler licenses"],[0,1,2],"CPU cycles, main memory, file storage and I/O devices are allocated. Compiler licenses are not."],
["Which requires user authentication?",["Security","Protection","Accounting","Batch processing"],[0],"Security from outsiders requires user authentication. Protection is about controlling access."],
["If shell commands are just program names, adding new features...",["needs no shell modification","requires recompiling the kernel","is impossible","requires a GUI"],[0],"Commands that are program names can be added without modifying the shell."],
["MATLAB has a CLI but is not a...",["command-line interpreter","GUI","system call","wrapper"],[0],"MATLAB has a command line interface but is an application, not a stand-alone command-line interpreter."],
["macOS uses which GUI over a UNIX kernel?",["Aqua","CDE","KDE","GNOME"],[0],"macOS uses the Aqua GUI over a UNIX kernel. CDE, KDE and GNOME are Unix/Linux GUIs."],
["Which GUIs are built on X11 or Wayland?",["CDE","KDE","GNOME","Aqua"],[0,1,2],"CDE, KDE and GNOME are built on X11 or Wayland. Aqua belongs to macOS."],
["What does a wrapper do on the way to a system call?",["Switches to kernel mode and jumps to the handler","Runs entirely in kernel mode","Replaces the kernel","Compiles the program"],[0],"Inside the wrapper, code switches to kernel mode and jumps to the system call handler."],
["When a program 'calls a system call', it technically calls...",["the wrapper function in the API library","the kernel function directly","the shell","the hypervisor"],[0],"Programs technically call the library's wrapper, which then invokes the system call."]]});
