LECTURES.push({n:8,title:"Lecture 8: Process Scheduling, Operations, IPC",
cards:[
["Process scheduling","Assigning resources (disk, memory, CPU or core) to units of work (threads, processes, jobs). Goals: better hardware utilization, minimal response time, fairness."],
["Three levels of scheduling","Long-term: which processes are admitted (mostly batch). Medium-term: which are memory-resident. Short-term (CPU scheduling): which memory-resident process gets the CPU next."],
["Medium-term scheduling","Controls the degree of multiprogramming (number of processes in memory) and the process mix. Too few: CPU idle. Too many: not enough memory."],
["I/O-bound vs compute-bound","I/O-bound: run briefly, then issue I/O requests. Compute-bound: spend most time computing. A good mix keeps the CPU busy with low response times."],
["Ready and wait queues","Ready queue: memory-resident processes ready but not running. A wait queue per device holds processes waiting for that device. Queues hold pointers to PCBs."],
["CPU scheduler","Picks from the ready queue to maximize CPU utilization and minimize response time. It runs very often in interactive systems, so it must be extremely fast."],
["Process queuing","A running process that issues I/O goes to the device's wait queue; once serviced it goes to the rear of the ready queue. Processes move between queues until they terminate."],
["Context switch","CPU switches processes: save the old process state in its PCB and load the new one's. Pure overhead; a more complex OS and PCB means a longer switch. Multiple register sets per CPU reduce it."],
["Process creation and fork()","Parents create children, forming a process tree; each has a pid. fork() makes a near-exact copy and both continue after the call: parent gets the child's pid, child gets 0. getpid() returns the caller's pid."],
["Termination, zombie, orphan","exit() ends a process; status returns to the parent via wait(). A parent may abort() a child (over resources, task not needed, parent exiting). Zombie: terminated, parent has not called wait(). Orphan: parent terminated without wait()."],
["Concurrency and cooperation","Processes are concurrent if their computations can overlap in time. Independent: neither affects the other. Cooperating: each can affect the other. Reasons: data sharing, computation speedup, modularity."],
["Chrome's processes","Browser process (UI, disk and network I/O), a renderer process per website (so one faulty site does not affect others), and a plug-in process per plug-in type."],
["Two IPC models","Shared memory (same machine only; processes must synchronize access; threads share an address space) and message passing (send/receive; works across machines)."],
["Message passing details","Messages can be fixed or variable size. MPI is the most popular library (OpenMPI on Linux). A communication link or channel is a reliable logical queue: data arrive in order, none lost or duplicated."],
["exec()","After fork(), a process typically calls exec() to replace its memory space with a new program: it loads a binary into memory (destroying the old image) and starts it."],
["Producer-consumer","Common paradigm for cooperating processes: a producer creates information that a consumer uses (compiler to assembler to loader)."],
["Direct vs indirect communication","Direct: each process explicitly names the other. Indirect: messages go to and from mailboxes (ports)."],
["Synchronous vs asynchronous","Blocking (synchronous) vs nonblocking (asynchronous) send and receive. If both send and receive block, there is a rendezvous."],
["Buffering capacity","Zero capacity: sender blocks until the receiver takes the message. Bounded capacity: queue of length n, sender blocks when full. Unbounded: sender never blocks."],
["Pipes","Ordinary pipes: unidirectional (write end, read end), parent-child, vanish when the processes finish. Named pipes: bidirectional, no parent-child needed, several writers, persist afterward."],
["Sockets and RPC","A socket is an endpoint for communication, identified by an IP address plus a port number (client-server). RPC abstracts procedure calls between processes on networked systems."]],
qs:[
["Medium-term scheduling controls...",["the degree of multiprogramming","which batch job is admitted","which instruction runs next","bus arbitration"],[0],"It decides how many and which processes are in memory."],
["A process that runs briefly and then issues I/O requests is...",["I/O-bound","compute-bound","a zombie","an orphan"],[0],"Compute-bound processes spend most time computing."],
["The ready queue holds...",["memory-resident processes that are ready but not running","processes waiting for I/O","terminated processes","only the running process"],[0],"Waiting processes sit in device wait queues."],
["Why must the CPU scheduler be extremely fast?",["It runs very frequently, so slowness adds overhead and hurts throughput and response time","It manages the disk","It runs only at boot","It schedules only batch jobs"],[0],"Scheduling overhead lowers CPU utilization."],
["When we say a queue contains processes, it holds...",["pointers to their PCBs","copies of their memory","their open files","their code"],[0],"The PCB represents the process."],
["Which of the following is/are true of a context switch?",["Saves the old process state and loads the new one","It is pure overhead","A more complex OS and PCB makes it longer","It does useful work for the user"],[0,1,2],"No useful work is done while switching."],
["Which of the following is/are true after fork()?",["Two processes exist, each continuing after the call","The parent gets the child's pid","The child gets 0","The child restarts main from the beginning"],[0,1,2],"Both continue right after the fork() call."],
["A terminated process whose parent has not called wait() is a...",["zombie","orphan","daemon","thread"],[0],"An orphan's parent terminated without calling wait()."],
["Why might a parent abort() a child?",["Child exceeded allocated resources","Task no longer required","Parent is exiting and the OS does not allow orphans","Child printed output"],[0,1,2],"Printing output is not a reason."],
["Which of the following is/are reason(s) for process cooperation?",["Data sharing","Computation speedup","Modularity","Always lower memory use"],[0,1,2],"Cooperation is not about memory savings."],
["Why does Chrome create a renderer process per website?",["Problems in one website do not affect others","To save memory","Plug-ins require it","To do disk I/O"],[0],"The browser process handles disk and network I/O."],
["Which of the following is/are the two general IPC models?",["Shared memory and message passing","Pipes and files only","Interrupts and DMA","Shell and GUI"],[0],"Both are supported by the kernel."],
["Shared memory IPC can be used only when processes...",["run on the same machine","are on different continents","are threads only","use MPI"],[0],"Message passing works across machines."],
["Which of the following is/are true of message passing?",["Processes need not be on the same machine","Primitives are send and receive","MPI is the most popular library","Requires a shared address space"],[0,1,2],"Sharing an address space is the shared memory model."],
["A reliable channel guarantees...",["data arrive in the order sent","no data are lost","no data are duplicated","data arrive instantly"],[0,1,2],"It says nothing about speed."],
["After fork(), a child typically uses exec() to...",["replace its memory space with a new program","create another child","wait for the parent","terminate"],[0],"exec() loads a binary and destroys the old image."],
["In the producer-consumer problem, the consumer...",["uses information produced by the producer","produces the information","terminates the producer","schedules the CPU"],[0],"E.g. an assembler consumes a compiler's output."],
["Indirect communication uses...",["mailboxes (ports)","explicit naming of the receiver","shared variables only","interrupts"],[0],"Direct communication names the other process."],
["If both send() and receive() block, there is a...",["rendezvous","deadlock","zombie","orphan"],[0],"Sender and receiver meet at the transfer."],
["Zero capacity buffering means...",["the sender blocks until the receiver takes the message","an unlimited queue","messages are lost","the receiver blocks forever"],[0],"There is no queue to hold waiting messages."],
["Which of the following is/are true of ordinary pipes?",["Unidirectional","Used between parent and child","Gone after the processes finish","Usable by unrelated processes"],[0,1,2],"Named pipes serve unrelated processes and persist."],
["A socket is identified by...",["an IP address concatenated with a port number","a pid","a file name","an MPI rank"],[0],"A pair of sockets connects two processes."]]});
