LECTURES.push({n:2,title:"Lecture 2: I/O, Interrupts, DMA, Buses",
cards:[
["I/O module functions","Control and timing, CPU communication, device communication, data buffering, error detection."],
["Programmed I/O","Processor directly controls the I/O operation and must wait until it completes. Wasteful if the processor is faster."],
["Interrupt-driven I/O","Processor issues the command, keeps executing other instructions, and is interrupted when the I/O module finishes."],
["DMA","I/O module and main memory exchange data directly without processor involvement. The controller takes over the bus with CPU permission."],
["Cycle stealing","DMA uses the bus when the CPU is not going to, so the CPU can keep working."],
["Identifying the interrupting module","Software poll (slow); daisy chain / hardware poll (module places vector on bus); bus arbitration (module claims bus first)."],
["Simple interrupt processing","Hardware: finish instruction, acknowledge, push PSW and PC on control stack, load new PC. Software: save state, process, restore state, restore PSW and PC."],
["Bus","Shared communication link (one set of wires) connecting subsystems. Versatile and low cost, but a bandwidth bottleneck."],
["I/O problems","Peripherals vary in data amount, speed and format; many are not connected directly to the bus; most are slower than CPU and RAM; word length and data format (e.g. parity bits) may differ from the CPU."],
["I/O module's two major functions","Interface to the processor or memory via the bus; interface to one or more peripherals via tailored data links."],
["Interrupt-driven I/O steps","CPU issues read; I/O module gets data while CPU does other work; module interrupts CPU; CPU requests data; module transfers data. No repeated CPU checking of the device."],
["DMA setup","CPU tells the DMA controller: read/write, device address, starting memory address, amount of data, mode. The controller transfers over the system bus, releases the bus, then interrupts the CPU."],
["DMA configurations","1) Single bus, detached DMA: bus used twice, CPU suspended twice. 2) Single bus, integrated DMA: bus once, may support several devices. 3) Separate I/O bus: bus once, supports all DMA devices."],
["I/O and the OS","The OS is the interface between I/O hardware and programs: gives device commands, handles interrupts, provides equitable access, and schedules I/O to improve throughput. I/O interrupts transfer control to the OS."],
["Bus pros and cons","Pros: versatile and scalable (devices added or moved easily), low cost (shared wires). Con: communication bottleneck, since bandwidth limits maximum I/O throughput. Speed limited by bus length and number of devices."],
["Bus characteristics","Control lines: signal requests and acknowledgments, say what is on the data lines. Data lines: data, addresses, complex commands. A transaction is a request (initiator) plus an action (responder); input = device to memory, output = memory to device."]],
qs:[
["Which I/O technique makes the CPU wait until the operation completes?",["Programmed I/O","Interrupt-driven I/O","DMA","None of these"],[0],"The processor polls status."],
["When a DMA transfer finishes, the controller...",["releases the bus","sends an interrupt to the CPU","waits for the CPU to copy the data","shuts down the system"],[0,1],"DMA needs no CPU copying."],
["Which DMA configuration uses the bus twice per transfer and suspends the CPU twice?",["Single bus, detached DMA","Single bus, integrated DMA","Separate I/O bus","None"],[0],"I/O to DMA, then DMA to memory."],
["In the separate I/O bus DMA configuration, how many times is the CPU suspended per transfer?",["0","1","2","3"],[1],"Only the DMA-to-memory transfer uses the system bus."],
["What is cycle stealing?",["DMA uses the bus when the CPU will not, so the CPU keeps working","DMA suspends the CPU for the whole transfer","The CPU takes cycles from the I/O module","An interrupt is ignored"],[0],"It is an alternative to suspending the CPU."],
["Why can user programs not talk to I/O devices directly?",["To protect shared I/O resources","Devices are too slow","User programs lack memory","To save power"],[0],"The OS mediates I/O."],
["Which are limits or disadvantages of a bus?",["Communication bottleneck","Speed limited by bus length","Speed limited by number of devices","New devices cannot be added"],[0,1,2],"Buses are versatile and scalable."],
["What does the processor do right after a device issues an interrupt?",["Finishes the current instruction","Saves all registers to disk","Loads the handler mid-instruction","Discards the instruction"],[0],"Then it acknowledges the interrupt."],
["What is pushed onto the control stack on an interrupt?",["PSW and PC","Only data registers","The heap","The file table"],[0],"They are restored afterward."],
["Which method of identifying the interrupting module is described as slow?",["Software poll","Daisy chain","Bus arbitration","Vectored interrupt"],[0],"The CPU asks each module in turn."],
["How are multiple interrupts handled?",["Each line has a priority; higher priority can interrupt lower","First come first served only","Lowest priority first","Extra interrupts are ignored"],[0],"Priority decides."],
["Which are carried on a bus's data lines?",["Data","Addresses","Complex commands","Request acknowledgments"],[0,1,2],"Acknowledgments travel on control lines."],
["Which are I/O problems?",["Peripherals are mostly slower than CPU and RAM","Word length may differ from the CPU","Data formats may vary","All peripherals connect directly to the bus"],[0,1,2]],
["Which are major functions of an I/O module?",["Interface to processor/memory via the bus","Interface to peripherals via tailored links","Execute user programs","Schedule processes"],[0,1]],
["After issuing a read in interrupt-driven I/O, the CPU...",["continues executing other instructions","polls the device repeatedly","waits idle","starts a DMA transfer"],[0]],
["Which does the CPU give the DMA controller?",["Device address","Starting memory address","Amount of data to transfer","The user's password"],[0,1,2]],
["Which DMA configuration puts all DMA-enabled devices on their own bus?",["Separate I/O bus","Single bus, detached","Single bus, integrated","None"],[0]],
["Which are advantages of a bus?",["Versatile and scalable","Low cost","No bandwidth limit","Devices can move between systems using the same bus standard"],[0,1,3]],
["Maximum bus speed is largely limited by...",["Length of the bus","Number of devices on the bus","Cable color","Size of main memory"],[0,1]],
["Which does the OS do for I/O?",["Give commands to devices","Handle I/O interrupts","Provide equitable access","Let user programs control devices directly"],[0,1,2]]]});
